### PR TITLE
Mostly functional Chromium patch

### PR DESCRIPTION
**Pull request by rcelyte**
*Chromium is extremely cumbersome to build on my machine, so this code has only been tested in a component build with debug checks **disabled**. However, the Vulkan code has at least been tested to pass validation layers without warnings.*

Much of Chromium's OpenXR code has been refactored in the time since the existing patches. There is no longer a hard dependency on DirectX, and Android support brought with it much cleaner OS-agnostic abstractions to build off of.

This patch makes use of Vulkan's DMA-BUF extensions to feed images through the `GpuMemoryBuffer` interface. This removes a dependency on X11 and avoids the mess of OpenGL bugs present in SteamVR. Besides swapchain resizing and sandbox support, this *should* have feature parity with WebXR on Windows.

For some reason the mirrored view on the canvas freezes while WebXR is active. I'm not quite sure why this happens, but it doesn't seem to impact the image displayed in-headset.

### CODE REVIEW

**Comment by mrxz** [comment]
Awesome! Going to give it a test-drive and then it can probably be merged. I know a lot of people will be real happy with this :slightly_smiling_face: 

It's good to know that the upstream Chromium code has been refactored and improved since. That hopefully also mean it will be relatively easy to keep this patch up-to-date.

**Comment by mrmetaverse** [comment]
Amazing work! Really wanted this

**Comment by mrxz** [comment]
@rcelyte Got it working on my end, almost forgot how tedious compiling chromium is. I did have to make two small tweaks, however:

- Add `DEVICE_VR_EXPORT` to the `OpenXrPlatformHelperLinux` class, otherwise it wouldn't link
- Ensuring the same `libvulkan.so` was loaded as Chrome used, either replacing the `libvulkan.so.1` with my system one or changing the code to load `libvulkan.so.1` worked. Otherwise `xrGetVulkanGraphicsDevice2KHR` would fail inside SteamVR with:
  ```
  IVRSystem::GetOutputDevice: Failed to get required Vulkan device function pointer (vkGetPhysicalDeviceProperties2KHR)!
  ```
  Not sure what's going on, as that function pointer _is_ available (same issue, but with OpenVR: https://github.com/ValveSoftware/openvr/issues/1497).

It would be nice if others could test to verify both findings. Otherwise I'd suggest we simply add `DEVICE_VR_EXPORT` and merge it. Further fixes and improvements can always be made down the line. I'm already overjoyed to see a picture show up in my headset :slightly_smiling_face:

**Comment by rcelyte** [comment]
> Add `DEVICE_VR_EXPORT`

Odd that I didn't encounter this in my testing. Is there a specific build configuration needed for it to become meaningful?

> `libvulkan.so.1`

Whoops, I didn't realize Chromium shipped with its own Vulkan loader without the base name as an alias. Guess the one on my system just happened to be compatible with that x_x

**Comment by mrxz** [comment]
> Odd that I didn't encounter this in my testing. Is there a specific build configuration needed for it to become meaningful?

It's only really a thing with component builds AFAIK, but other than that I'm not aware of any specific configuration. For what it's worth, I used an almost vanilla Debug configuration, only disabling some debug symbols and NaCl

**Comment by rcelyte** [comment]
I was using a component build o_0

**Pull request merged**
